apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-systems
  description: A collection of all Backstage example systems
spec:
  targets:
    - ./systems/iam-client-app-system.yaml
    - ./systems/iam-connected-app-system.yaml
