apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: connected-app
  description: This component represents a connected app
  annotations:
    azure.com/portal-link: "https://portal.azure.com/#resource/..."
spec:
  type: connected-app
  owner: group:default/dna-daas-di-sirius-mudders
  system: iam-system
  lifecycle: production
  providesApis:
    - prc-identity-access-management-api

